### ISSUE TITLE
Is there a way to directly use the standard output of rmats to connect to the GeneAPP workflow?

### ISSUE THREAD

**Issue by mumdark** [MiqueiasFernandes/GeneAPP#5]
Thank you for developing such an excellent tool!

Is there a way to directly use the standard output of rmats to connect to the GeneAPP workflow?

**Comment by MiqueiasFernandes** [comment]
Hello mumdark,
thanks!

yes, you can do it by clicking "New project" in "Data enrichment and augmentation" on https://geneapp.net/new
load your GFF3 and rmats/3drnaseq output tables then click in "Submit" button.
This step consumes backend resources, then are a queue, if has no slot in our server the button will be hidden.
